# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable the Corne OLED Display
# CONFIG_ZMK_DISPLAY=y

# Set deep sleep timeout to 60 minutes
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Change board name
CONFIG_ZMK_KEYBOARD_NAME="Pandoks_ Corne"

# Improve BLE connection stability (disables 2M PHY)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Increase BLE transmit power to +8 dBm
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Preferred BLE connection interval (units of 1.25ms)
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
